# Production Swarm configuration
services:
    champdavoine:
        build:
            target: production
        image: thegobc/champdavoine
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.champdavoine.rule=Host(`champdavoine.com`)'
            - 'traefik.http.routers.champdavoine.entrypoints=websecure'
            - 'traefik.http.routers.champdavoine.tls.certresolver=myresolver'
        environment:
            NODE_ENV: production
        networks:
            - webnet

networks:
    webnet:
        external: true
